# Generated by Django 4.0.4 on 2022-04-27 03:18

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_event_confirmed_remove_event_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True, validators=[home.models.date_validator]),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(null=True, validators=[home.models.date_validator]),
        ),
        migrations.AddField(
            model_name='event',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.trip'),
        ),
    ]
