# Generated by Django 4.0.4 on 2022-05-02 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_event_confirmed_event_cost_event_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Going',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(related_name='members_going', through='home.Going', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='going',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trip'),
        ),
        migrations.AddField(
            model_name='going',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
