# Generated by Django 4.0.4 on 2022-05-02 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_trip_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='key',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Trip key must be longer than 3 characters')]),
        ),
    ]
