# Generated by Django 4.0.4 on 2022-05-05 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')]),
        ),
    ]
