# Generated by Django 4.0.4 on 2022-05-06 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likers',
            field=models.ManyToManyField(related_name='comment_likers', through='home.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
