# Generated by Django 4.0.4 on 2022-05-09 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_photos_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_photos', to='home.trip'),
        ),
    ]
