# Generated by Django 4.0.4 on 2022-05-11 08:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0026_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Group title must be longer than 3 characters')])),
                ('key', models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Group key must be longer than 3 characters')])),
                ('description', models.TextField(default="A cool group for a cool 'group' of people :)", max_length=200)),
                ('start_date', models.DateField(validators=[home.models.date_validator])),
                ('end_date', models.DateField(validators=[home.models.date_validator])),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='event',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='going',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='trip',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members_going', through='home.Going', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.group'),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.group'),
        ),
        migrations.AddField(
            model_name='going',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.group'),
        ),
        migrations.AddField(
            model_name='photos',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_photos', to='home.group'),
        ),
    ]
