# Generated by Django 4.0.4 on 2022-05-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_group_end_date_remove_group_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(choices=[('buildings.png', 'Buildings'), ('europe.png', 'Europe'), ('forest.png', 'Forest'), ('grand-canyon.png', 'Japan'), ('mountain.png', 'Moutains'), ('united-states.png', 'USA'), ('vacations.png', 'Beach')], max_length=128, null=True),
        ),
    ]
