# Generated by Django 4.0.4 on 2022-05-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_group_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.CharField(blank=True, choices=[('buildings.png', 'Buildings'), ('europe.png', 'Europe'), ('forest.png', 'Forest'), ('grand-canyon.png', 'Grand Canyon'), ('japan.png', 'Japan'), ('mountain.png', 'Moutains'), ('united-states.png', 'USA'), ('vacations.png', 'Beach')], max_length=128, null=True),
        ),
    ]
